// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OAuthMvcSample.Data;

#nullable disable

namespace OAuthMvcSample.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251116210657_InitialAppSchema")]
    partial class InitialAppSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("OAuthMvcSample.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Information Technology",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Human Resources",
                            Name = "HR"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Financial Department",
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("OAuthMvcSample.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john.smith@example.com",
                            FullName = "John Smith",
                            HireDate = new DateTime(2024, 10, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "anna.johnson@example.com",
                            FullName = "Anna Johnson",
                            HireDate = new DateTime(2023, 5, 15, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 3
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "michael.brown@example.com",
                            FullName = "Michael Brown",
                            HireDate = new DateTime(2022, 3, 20, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 4
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "emily.davis@example.com",
                            FullName = "Emily Davis",
                            HireDate = new DateTime(2024, 1, 10, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            PositionId = 2
                        });
                });

            modelBuilder.Entity("OAuthMvcSample.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Entry-level developer",
                            Name = "Junior Developer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Experienced developer",
                            Name = "Senior Developer"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Manages HR processes",
                            Name = "HR Manager"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Handles company finances",
                            Name = "Accountant"
                        });
                });

            modelBuilder.Entity("OAuthMvcSample.Models.Employee", b =>
                {
                    b.HasOne("OAuthMvcSample.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OAuthMvcSample.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("OAuthMvcSample.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("OAuthMvcSample.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
